name: macOS-build

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  macOS-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make setup
      run: make setup
    - name: make
      run: make
