name: Platform Build

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  macOS-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: mingw32-make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
