
name: Windows

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: make setup
      working-directory: D:/a/raylib-cpp-starter
      run: mingw32-make setup
      shell: cmd
      
    - name: make compile
      working-directory: D:/a/raylib-cpp-starter
      run: mingw32-make compile
      shell: cmd
      
    - name: make clean
      working-directory: D:/a/raylib-cpp-starter
      run: mingw32-make clean
      shell: cmd

    - name: make compile CXX=g++
      working-directory: D:/a/raylib-cpp-starter
      run: mingw32-make compile CXX=g++
      shell: cmd
  
    - name: make clean
      working-directory: D:/a/raylib-cpp-starter
      run: mingw32-make clean
      shell: cmd
