
name: Windows

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: make setup
      run: mingw32-make setup
      shell: bash
      
    - name: make compile
      run: mingw32-make compile
      shell: bash
      
    - name: make clean
      run: mingw32-make clean
      shell: bash

    - name: make compile CXX=g++
      run: mingw32-make compile CXX=g++
      shell: bash
  
    - name: make clean
      run: mingw32-make clean
      shell: bash
